name: Java CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[SKIP-CI]')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-java-version: [ 21 ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.build-java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.build-java-version }}
          cache: 'gradle'

      - name: Update Gradle Dev Version to 1.0.0-dev#${{ matrix.build-java-version }}
        run: |
          COMMIT_HASH="${GITHUB_SHA::7}"
          BASE_VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')
          sed -i "s|^version=.*|version=${BASE_VERSION}-dev#${COMMIT_HASH}|" gradle.properties
          cat gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean check build

      - name: Upload artifact for Java ${{ matrix.build-java-version }}
        uses: actions/upload-artifact@v4
        with:
          name: IdenticaLimbo-java${{ matrix.build-java-version }}
          path: build/IdenticaLimbo-*.jar
